# Generated by Django 6.0.3 on 2026-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Permite que los visitantes envien comentarios a esta publicacion.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Desmarcar para ocultar el comentario (moderaciÃ³n).'),
        ),
    ]
