# Generated by Django 6.0.3 on 2026-03-29 05:42

import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_news_pages'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Etiquetas del post (ej: madres-comunitarias, derecho, educacion)', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Desmarcar para ocultar el comentario (moderacion).'),
        ),
    ]
