# Generated by Django 6.0.3 on 2026-03-31 03:23

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_tags_alter_comment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revision'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de consultoria',
                'verbose_name_plural': 'Solicitudes de consultoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=blog.models.consultation_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.consultationrequest')),
            ],
            options={
                'verbose_name': 'Adjunto de consultoria',
                'verbose_name_plural': 'Adjuntos de consultoria',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
