# Generated by Django 6.0.3 on 2026-05-08 02:43

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_consultationrequest_consultationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author_display_name',
            field=models.CharField(blank=True, help_text="Nombre publico del autor. Usar 'Autor anonimo' si la publicacion invitada debe ocultar identidad.", max_length=150),
        ),
        migrations.CreateModel(
            name='GuestPostSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('author_image', models.URLField(blank=True, default='')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('suggested_tags', models.CharField(blank=True, max_length=250)),
                ('publish_anonymously', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revision'), ('draft_created', 'Borrador creado'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('editorial_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_blog_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_submissions', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'Publicacion invitada',
                'verbose_name_plural': 'Publicaciones invitadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=blog.models.guest_post_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.guestpostsubmission')),
            ],
            options={
                'verbose_name': 'Adjunto de publicacion invitada',
                'verbose_name_plural': 'Adjuntos de publicaciones invitadas',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
